#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure Nginx to include custom HTTP response header
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx service
sudo systemctl restart nginx
