#!/usr/bin/env bash
# Install Nginx if not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Check Nginx Status
if systemctl is-active --quiet nginx
then
    # Nginx is already running.
    :
else
    sudo systemctl start nginx
fi

# Check Nginx Configuration
if sudo nginx -t | grep -q "syntax is okay"
then
    # Nginx configuration test passed.
    :
else
    exit 1
fi

# Edit Nginx Configuration
if ! grep -q "listen 80;" /etc/nginx/sites-available/default
then
    sudo sed -i '/server {/a \    listen 80;' /etc/nginx/sites-available/default
    sudo systemctl reload nginx
fi


