#!/usr/bin/env bash
# prints string 10 times with a loop
counter=1
while [ $counter -le 10 ]
do
if [ $counter == 4 ]
then
    echo bad luck
    ((counter++))
elif [ $counter == 8 ]
then
    echo good luck
    ((counter++))
else
    echo Holberton School
    ((counter++))
fi
done
