#!/usr/bin/env bash
# prints string 10 times with a loop
counter=1
while [ $counter -le 20 ]
do
    case $counter in
	4) echo $counter
	    echo bad luck from China
	    ((counter++))
	    ;;
	9) echo $counter
	    echo bad luck from Japan
	    ((counter++))
	    ;;
       17) echo $counter
	    echo bad luck from Italy
	    ((counter++))
	    ;;
    esac
    echo $counter
((counter++))
done
