#!/usr/bin/env bash
#modify the host file
# Copy the original /etc/hosts to a temporary file
sudo cp /etc/hosts ~/hosts.new

# Modify the temporary file using sed (example: add 127.0.0.2 localhost)
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Copy the modified temporary file back to /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts
